apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail
  namespace: wordpress-stack
  annotations:
    # kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        - mail.dwsclass.io
      secretName: mail.dwsclass
  rules:
    - host: mail.dwsclass.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail
                port:
                  number: 80
