---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mail-storage         
  namespace: wordpress-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
