---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  hostPath:
    path: /mnt/vol-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  hostPath:
    path: /mnt/vol-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-03
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  hostPath: 
    path: /mnt/vol-03
