---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wordpress-storage
  namespace: wordpress-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
