---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-credentials
  namespace: wordpress-stack
type: opaque
stringData:            
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_USER: admin
  WORDPRESS_DB_PASSWORD: strong-user-pass
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_TABLE_PREFIX: ir_ 
