---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage
  namespace: wordpress-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
