---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: wordpress-stack
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: stong-root-password
  MYSQL_DATABASE: wordpress
  MYSQL_USER: admin
  MYSQL_PASSWORD: strong-user-pass
